// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protodata.proto

/*
Package proto2 is a generated protocol buffer package.

mirrors the animal structs that we use in the database layer
type animal struct {
	id         int
	animalType string
	nickname   string
	zone       int
	age        int
}

It is generated from these files:
	protodata.proto

It has these top-level messages:
	Animal
*/
package proto2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Animal struct {
	Id               *int32  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	AnimalType       *string `protobuf:"bytes,2,req,name=animal_type" json:"animal_type,omitempty"`
	Nickname         *string `protobuf:"bytes,3,opt,name=nickname" json:"nickname,omitempty"`
	Zone             *int32  `protobuf:"varint,4,req,name=zone" json:"zone,omitempty"`
	Age              *int32  `protobuf:"varint,5,opt,name=age" json:"age,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Animal) Reset()                    { *m = Animal{} }
func (m *Animal) String() string            { return proto.CompactTextString(m) }
func (*Animal) ProtoMessage()               {}
func (*Animal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Animal) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Animal) GetAnimalType() string {
	if m != nil && m.AnimalType != nil {
		return *m.AnimalType
	}
	return ""
}

func (m *Animal) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *Animal) GetZone() int32 {
	if m != nil && m.Zone != nil {
		return *m.Zone
	}
	return 0
}

func (m *Animal) GetAge() int32 {
	if m != nil && m.Age != nil {
		return *m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*Animal)(nil), "proto2.animal")
}

func init() { proto.RegisterFile("protodata.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x49, 0x2c, 0x49, 0xd4, 0x03, 0xb3, 0x84, 0xd8, 0xc0, 0x94, 0x91, 0x52, 0x18, 0x17,
	0x5b, 0x62, 0x5e, 0x66, 0x6e, 0x62, 0x8e, 0x10, 0x17, 0x17, 0x53, 0x66, 0x8a, 0x04, 0xa3, 0x02,
	0x93, 0x06, 0xab, 0x90, 0x30, 0x17, 0x37, 0x44, 0x34, 0xbe, 0xa4, 0xb2, 0x20, 0x55, 0x82, 0x49,
	0x81, 0x49, 0x83, 0x53, 0x48, 0x80, 0x8b, 0x23, 0x2f, 0x33, 0x39, 0x3b, 0x2f, 0x31, 0x37, 0x55,
	0x82, 0x59, 0x81, 0x51, 0x83, 0x53, 0x88, 0x87, 0x8b, 0xa5, 0x2a, 0x3f, 0x2f, 0x55, 0x82, 0x05,
	0xac, 0x89, 0x9b, 0x8b, 0x39, 0x31, 0x3d, 0x55, 0x82, 0x55, 0x81, 0x51, 0x83, 0x15, 0x10, 0x00,
	0x00, 0xff, 0xff, 0x9c, 0xb1, 0x42, 0xb5, 0x71, 0x00, 0x00, 0x00,
}
