
				// Code generated by hero.
			// source: /Users/Leland/go/go_code/udemy/modern_go/project_dino/dino/webportal/template/index.html
				// DO NOT EDIT!
			package template

				import "html"
				import "unsafe"

				import "github.com/shiyanhui/hero"
			